name: Repo Test Workflow

on: 
  workflow_dispatch:
  
jobs:  
  run-api-tests:
    name: Run tests
    runs-on: ubuntu-20.04
    
    steps:
      - name: Create short sha of current checked out commit
        run: echo "LOCAL_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    
      - uses: actions/checkout@v2
      - name: Run API tests
        uses: actions/github-script@v6
        env:
          OWNER: "sanyar123"
          REPO: "flink-weather-shopper"
          WORKFLOW_ID: "weather-shopper.yml"
          SCRIPT_PATH: ".github/workflows/script.js"
          COMMIT_HASH: "${{ env.LOCAL_SHORT_SHA }}"
        with:
          github-token: ${{ secrets.CROSS_REPOSITORY_ACCESS_TOKEN }}
          script: |
            const runScript = require(`${process.env.GITHUB_WORKSPACE}/${process.env.SCRIPT_PATH}`);
            runScript({ context, github, core });
            
  jobtest:
    runs-on: ubuntu-latest
    steps:
      - run: date
